package com.foto.nick.quarksonline;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Title: RulesOfAcquisition.java
 * Author: Nicholas Fotinakes
 * Abstract: This class stores and generates a random rule of acquisition to display as a toast
 * Date: 12-10-2021
 */
public class RulesOfAcquisition {
    private List<String> rules;

    // Constructor initializes list with rules
    public RulesOfAcquisition(){
        rules = new ArrayList<>();
        rules.add("Rule #1: Once you have their money, you never give it back.");
        rules.add("Rule #2: The best deal is the one that brings the most profit.");
        rules.add("Rule #3: Never spend more for an acquisition than you have to.");
        rules.add("Rule #4: Time and Latinum are precious.");
        rules.add("Rule #5: Always exaggerate your estimate.");
        rules.add("Rule #6: Never allow family to stand in the way of opportunity.");
        rules.add("Rule #7: Keep your ears open.");
        rules.add("Rule #8: Small print leads to large risk.");
        rules.add("Rule #9: Opportunity plus instinct equals profit.");
        rules.add("Rule #10: Greed is eternal.");
        rules.add("Rule #11: Even if it's free, you can always buy it cheaper");
        rules.add("Rule #12: Anything worth selling is worth selling twice.");
        rules.add("Rule #13: Anything worth doing is worth doing for money.");
        rules.add("Rule #14: Keep your family close; keep your Latinum closer.");
        rules.add("Rule #15: Dead men close no deals.");
        rules.add("Rule #16: A deal is a deal, until a better one comes along.");
        rules.add("Rule #17: A contract is a contract is a contract: but only between Ferengi.");
        rules.add("Rule #18: A Ferengi without profit is no Ferengi at all.");
        rules.add("Rule #19: Satisfaction is not guaranteed.");
        rules.add("Rule #20: He who dives under the table today, lives to profit tomorrow.");
        rules.add("Rule #21: Never place friendship before profit.");
        rules.add("Rule #22: A wise man can hear profit in the wind.");
        rules.add("Rule #23: Nothing is more important than health, except money.");
        rules.add("Rule #24: Latinum can't buy happiness, but you can sure have a blast renting it.");
        rules.add("Rule #25: You pay for it, it's your idea.");
        rules.add("Rule #26: As the customers go, so goes the wise profiteer.");
        rules.add("Rule #27: There's nothing more dangerous than an honest businessman.");
        rules.add("Rule #28: Whisper your way to success.");
        rules.add("Rule #29: Always ask, \"What's in it for me?\"");
        rules.add("Rule #30: Talk is cheap, synthehol isn't.");
        rules.add("Rule #31: Never make fun of a Ferengi's mother.");
        rules.add("Rule #32: Be careful what you sell, it may do exactly what the customer expects.");
        rules.add("Rule #33: It never hurts to suck up to the boss.");
        rules.add("Rule #34: War is good for business.");
        rules.add("Rule #35: Peace is good for business.");
        rules.add("Rule #36: Neutrality is good for business.");
        rules.add("Rule #37: If it's free, take it and worry about hidden costs later.");
        rules.add("Rule #38: Everyone needs something.");
        rules.add("Rule #39: Friendship is temporary; profit is forever.");
        rules.add("Rule #40: She can touch your lobes, but never your Latinum.");
        rules.add("Rule #41: Profit is its own reward.");
        rules.add("Rule #42: What's mine is mine.");
        rules.add("Rule #43: What's yours can be mine.");
        rules.add("Rule #44: Never confuse wisdom with luck.");
        rules.add("Rule #45: Expand or Die.");
        rules.add("Rule #46: Make your shop easy to find.");
        rules.add("Rule #47: Don't trust a man wearing a better suit than your own.");
        rules.add("Rule #48: The bigger the smile, the sharper the knife.");
        rules.add("Rule #49: Everything is worth something to somebody.");
        rules.add("Rule #50: Gratitude can bring on generosity.");
        rules.add("Rule #51: Reward anyone who adds to your profits so they will continue to do so.");
        rules.add("Rule #52: Never ask when you can take.");
        rules.add("Rule #53: Never trust anybody taller than you.");
        rules.add("Rule #54: Never trust a Ferengi with bigger lobes.");
        rules.add("Rule #55: Advertise.");
        rules.add("Rule #56: Be discreet.");
        rules.add("Rule #57: Good customers are as rare as Latinum; treasure them.");
        rules.add("Rule #58: There is no substitute for success.");
        rules.add("Rule #59: Free advice is seldom cheap.");
        rules.add("Rule #60: Keep your lies consistent.");
        rules.add("Rule #61: Never underestimate the power of bribery.");
        rules.add("Rule #62: The riskier the road, the greater the profit.");
        rules.add("Rule #63: Share only what isn't yours.");
        rules.add("Rule #64: You don't need a store front to set up shop.");
        rules.add("Rule #65: Win or lose, there's always Huyperian beetle snuff.");
        rules.add("Rule #66: Double the price, then sell it half off.");
        rules.add("Rule #67: Always inspect the merchandise.");
        rules.add("Rule #68: A little ear stroking goes a long way.");
        rules.add("Rule #69: Ferengi are not responsible for the stupidity of other races.");
        rules.add("Rule #70: Ferengi are not responsible for the stupidity of other Ferengi.");
        rules.add("Rule #71: Close the deal, and then answer questions.");
        rules.add("Rule #72: Never trust your customers.");
        rules.add("Rule #73: If it gets you profit, sell your own mother");
        rules.add("Rule #74: Knowledge equals profit.");
        rules.add("Rule #75: Home is where the heart is, but the stars are made of Latinum.");
        rules.add("Rule #76: Every once in a while, declare peace. It confuses the hell out of your enemies.");
        rules.add("Rule #77: It's better to swallow your pride than to lose your profit.");
        rules.add("Rule #78: When the going gets tough, the tough change the Rules.");
        rules.add("Rule #79: Beware of the Vulcan greed for knowledge.");
        rules.add("Rule #80: Greed is known by many names.");
        rules.add("Rule #81: There's a difference between being a coward and running away.");
        rules.add("Rule #82: The flimsier the product, the higher the price.");
        rules.add("Rule #83: Even the wealth of the Nagus started with one slip of Latinum.");
        rules.add("Rule #84: A friend is not a friend if he asks for a discount.");
        rules.add("Rule #85: Never let the competition know what you're thinking.");
        rules.add("Rule #86: When the odds are against you never give up; just quit.");
        rules.add("Rule #87: A friend in need means three times the profit.");
        rules.add("Rule #88: It ain't over 'till it's over.");
        rules.add("Rule #89: Ask not what your profits can do for you, ask what you can do for your profits.");
        rules.add("Rule #90: The Divine Treasury awaits.");
        rules.add("Rule #91: Hear all, trust nothing.");
        rules.add("Rule #92: There are many paths to profit.");
        rules.add("Rule #93: Act without delay! The sharp knife cuts quickly");
        rules.add("Rule #94: Females and finances don't mix");
        rules.add("Rule #95: Prejudice only eliminates customers.");
        rules.add("Rule #96: For every Rule, there is an equal and opposite Rule (except when there's not.)");
        rules.add("Rule #97: Enough... is never enough.");
        rules.add("Rule #98: Every man has his price.");
        rules.add("Rule #99: Trust is the biggest liability of all.");
        rules.add("Rule #100: If they take your first offer, you either asked too little, or offered too much.");
        rules.add("Rule #101: The only value of a collectible is what you can get somebody else to pay for it.");
        rules.add("Rule #102: Nature decays, but Latinum lasts forever");
        rules.add("Rule #103: Sleep can interfere with negotiations.");
        rules.add("Rule #104: Faith moves mountains of inventory.");
        rules.add("Rule #105: Don't trust anyone who trusts you.");
        rules.add("Rule #106: There is no honor in poverty.");
        rules.add("Rule #107: A warranty is valid only if they can find you.");
        rules.add("Rule #108: Don't buy what you can't sell.");
        rules.add("Rule #109: Dignity and an empty sack is worth the sack.");
        rules.add("Rule #110: Playing dumb is often smart.");
        rules.add("Rule #111: Treat people in your debt like family, exploit them [ruthlessly].");
        rules.add("Rule #112: Never have sex with the boss' sister.");
        rules.add("Rule #113: Always have sex with the boss.");
        rules.add("Rule #114: The one in power defines morality.");
        rules.add("Rule #115: The best contract always has a lot of fine print.");
        rules.add("Rule #116: There's always a catch.");
        rules.add("Rule #117: Profit is the better part of valor.");
        rules.add("Rule #118: There is no profit in revenge.");
        rules.add("Rule #119: Never judge a customer by the size of his wallet, sometimes, good things come in small packages.");
        rules.add("Rule #120: Borrow on a handshake, lend in writing.");
        rules.add("Rule #121: Everything is for sale, including friendship.");
        rules.add("Rule #122: Do not forsake your profits and they will watch over you.");
        rules.add("Rule #123: Even a blind man can recognize the glow of Latinum.");
        rules.add("Rule #124: Diligent hands bring wealth.");
        rules.add("Rule #125: You can't make a deal if you're dead.");
        rules.add("Rule #126: Count it.");
        rules.add("Rule #127: Stay neutral in conflict so that you can sell supplies to both sides.");
        rules.add("Rule #128: Secrets are commodities, sell them.");
        rules.add("Rule #129: The fear of poverty is the beginning of knowledge.");
        rules.add("Rule #130: Never pay for sentiment, always charge for it.");
        rules.add("Rule #131: Information is profit.");
        rules.add("Rule #132: Never take no from someone who wasn't authorized to give you yes.");
        rules.add("Rule #133: Only those ideas that lead to profit are good.");
        rules.add("Rule #134: One good turn requires another.");
        rules.add("Rule #135: Never trust a beneficiary.");
        rules.add("Rule #136: Seek profit first and everything else will follow.");
        rules.add("Rule #137: Everything is negotiable.");
        rules.add("Rule #138: Wealth brings satisfaction.");
        rules.add("Rule #139: Wives serve, brothers inherit.");
        rules.add("Rule #140: Better great treasure with trouble than peace with poverty.");
        rules.add("Rule #141: Only fools pay retail.");
        rules.add("Rule #142: There's no such thing as an unfair advantage.");
        rules.add("Rule #143: Risk is part of the game... play it for all it's worth.");
        rules.add("Rule #144: There's nothing wrong with charity...as long as it winds up in your pocket.");
        rules.add("Rule #145: A little and often fills your pockets.");
        rules.add("Rule #146: Necessity is the mother of invention. Profit is the father.");
        rules.add("Rule #147: In all worthwhile labor there is profit.");
        rules.add("Rule #148: Wealth enables experience.");
        rules.add("Rule #149: Profit is encouragement to industry and enterprise.");
        rules.add("Rule #150: The way to become rich is to put all your Latinum in one sack, then watch the sack.");
        rules.add("Rule #151: The man is richest who's pleasures are cheapest.");
        rules.add("Rule #152: A lie is a way to tell the truth to someone who doesn't know.");
        rules.add("Rule #153: Sell the sizzle, not the steak.");
        rules.add("Rule #152: Work hard so you don't have to.");
        rules.add("Rule #153: When you have only 2 slips of Latinum left, buy bread with one, and bet the other.");
        rules.add("Rule #154: Pain passes, but profits remain.");
        rules.add("Rule #155: Power is 50% what you have and 50% what people think you have.");
        rules.add("Rule #156: Rainy days are good for business.");
        rules.add("Rule #157: Common sense is the collection of the customer's prejudices.");
        rules.add("Rule #158: The first principle of a rigid businessman is to always be flexible.");
        rules.add("Rule #159: There are no creeds in mathematics.");
        rules.add("Rule #160: Happiness is not mere possession of profit, but joy of acquisition.");
        rules.add("Rule #161: Beyond the mountains there are more mountains.");
        rules.add("Rule #162: Even in the worst of times, someone turns a profit.");
        rules.add("Rule #163: When a friend makes profit, you don't.");
        rules.add("Rule #164: Life does not guarantee equality of conditions, only of opportunity.");
        rules.add("Rule #165: Never let your sense of morals get in the way of opportunity.");
        rules.add("Rule #166: The success of any great transaction does not depend on odds.");
        rules.add("Rule #167: Earning is not only a duty it's a privilege.");
        rules.add("Rule #168: Whisper your way to success.");
        rules.add("Rule #169: Competition and fair play are mutually exclusive.");
        rules.add("Rule #170: The hand that feeds could be bitten.");
        rules.add("Rule #171: Blood is thicker than water, and Latinum is thicker than both.");
        rules.add("Rule #172: Chances aren't what they used to be.");
        rules.add("Rule #173: Dream, plan, believe, act.");
        rules.add("Rule #174: If you can't buy it, find someone who can.");
        rules.add("Rule #175: Gratitude is expensive.");
        rules.add("Rule #176: The wind always favors the best navigator.");
        rules.add("Rule #177: Know your enemies... but do business with them always.");
        rules.add("Rule #178: Power, leisure, and liberty are all words for profit.");
        rules.add("Rule #179: Opportunity may bring profit, friendship rarely does.");
        rules.add("Rule #180: Never discuss an opportunity with someone wealthier than you.");
        rules.add("Rule #181: Not even dishonesty can tarnish the shine of profit.");
        rules.add("Rule #182: The cost for profit is never too high.");
        rules.add("Rule #183: When it's a question of profit, everyone is of one belief.");
        rules.add("Rule #184: In the middle of difficulty lies opportunity.");
        rules.add("Rule #185: Small opportunities are often the beginning of great enterprises.");
        rules.add("Rule #186: There is no security, only opportunity.");
        rules.add("Rule #187: The philosophy of one is the common sense of another.");
        rules.add("Rule #188: A fool and his money are the best customer.");
        rules.add("Rule #189: Let others keep their reputation. You keep their money.");
        rules.add("Rule #190: Hear all, trust nothing.");
        rules.add("Rule #191: A Ferengi waits to bid until his opponents have exhausted themselves.");
        rules.add("Rule #192: Never cheat a Klingon... unless you're sure you can get away with it.");
        rules.add("Rule #193: Restlessness and discontent are the first necessities of desire.");
        rules.add("Rule #194: It's always good business to know about new customers before they walk in your door.");
        rules.add("Rule #195: You can't jump a 20 foot gorge in two 10 foot jumps.");
        rules.add("Rule #196: Listen to advice; then do what you want anyway.");
        rules.add("Rule #197: Pick battles big enough to matter, but small enough to win.");
        rules.add("Rule #198: You can't shake hands with a fist.");
        rules.add("Rule #199: The universe is not as difficult to comprehend as a Vulcan.");
        rules.add("Rule #200: A Ferengi chooses no side but his own.");
        rules.add("Rule #201: Wisdom consists of the anticipation of costs and consequences.");
        rules.add("Rule #202: The justification of profit is profit.");
        rules.add("Rule #203: New customers are like razor-backed Gree-worms... They can be succulent, but sometimes they bite back!");
        rules.add("Rule #204: It takes a Ferengi to cheat a Ferengi.");
        rules.add("Rule #205: Trust can be expensive.");
        rules.add("Rule #206: Distrust can be expensive.");
        rules.add("Rule #207: Sense without education is better than education without sense.");
        rules.add("Rule #208: Sometimes the only thing more dangerous than a question, is an answer.");
        rules.add("Rule #209: To many lobes spoil the deal.");
        rules.add("Rule #210: Always be smarter than the people you hire.");
        rules.add("Rule #211: Employees are the rungs on the ladder of success... don't hesitate to step on them.");
        rules.add("Rule #212: You and your Latinum are all you've got");
        rules.add("Rule #213: Those who concede to sell for less understand the value of business.");
        rules.add("Rule #214: Never begin a business negotiation on an empty stomach.");
        rules.add("Rule #215: Profit may not bring happiness, but there is no happiness without profit.");
        rules.add("Rule #216: Never gamble with an empath.");
        rules.add("Rule #217: You can't free a fish from water.");
        rules.add("Rule #218: Always know what you're buying.");
        rules.add("Rule #219: Possession is 11/10 of the law.");
        rules.add("Rule #220: Listen what they say while watching what they do.");
        rules.add("Rule #221: Computers can only give you the answers.");
        rules.add("Rule #222: The right to be heard does not automatically include the right to be believed.");
        rules.add("Rule #223: Beware the man who doesn't make time for oo-mox.");
        rules.add("Rule #224: Listen to your lobes");
        rules.add("Rule #225: Always follow one step ahead.");
        rules.add("Rule #226: Learn the language; translators malfunction.");
        rules.add("Rule #227: Emulation with profit is better than innovation with none.");
        rules.add("Rule #228: Bid high and bid often.");
        rules.add("Rule #229: Latinum lasts longer than lust.");
        rules.add("Rule #230: If they're smarter than you, make them a lesser partner.");
        rules.add("Rule #231: There's a customer born every minute; be sure you're the first to find each one.");
        rules.add("Rule #232: Deal only with select clientele. (Those who are rich and not so bright.)");
        rules.add("Rule #233: Latinum doesn't grow on trees.");
        rules.add("Rule #234: There's nothing wrong with a good delusion.");
        rules.add("Rule #235: Duck; death is tall.");
        rules.add("Rule #236: You can't buy fate");
        rules.add("Rule #237: It's good to want things, especially things you can't have.");
        rules.add("Rule #238: How I handle my business is none of yours.");
        rules.add("Rule #239: Never be afraid to mislabel a product.");
        rules.add("Rule #240: Do it yourself and keep it yourself.");
        rules.add("Rule #241: Never trust a hardworking employee.");
        rules.add("Rule #242: More is good... all is better.");
        rules.add("Rule #243: The more good will you can generate, the longer your customers stay.");
        rules.add("Rule #244: Because something's priceless doesn't mean it's not worthless.");
        rules.add("Rule #245: Benevolence is 50/50.");
        rules.add("Rule #246: Innocence is expensive.");
        rules.add("Rule #247: Don't negotiate with the underlings.");
        rules.add("Rule #248: Profit is in the details.");
        rules.add("Rule #249: Once it's sold stop selling.");
        rules.add("Rule #250: Precious things are for those that can prize them.");
        rules.add("Rule #251: Don't miss the opportunity by grabbing at the shadow.");
        rules.add("Rule #252: Little steps may prove great profit.");
        rules.add("Rule #253: Synthehol is the lubricant of choice for a customer's stuck purse.");
        rules.add("Rule #254: Better a fat slave than to starve free.");
        rules.add("Rule #255: A wife is a luxury... a smart accountant, a necessity");
        rules.add("Rule #256: Accountants do not play the game; they only keep the score.");
        rules.add("Rule #257: Despise the things you cannot have.");
        rules.add("Rule #258: A slip in the hand is better than a bar in sight.");
        rules.add("Rule #259: Wealth not yours might well as not exist.");
        rules.add("Rule #260: Life's not fair. How else would you turn a profit?");
        rules.add("Rule #261: A wealthy man can afford anything except a conscience.");
        rules.add("Rule #262: A verbal contract isn't worth the paper it's written on.");
        rules.add("Rule #263: Never allow doubt to tarnish your lust for Latinum.");
        rules.add("Rule #264: Distrust interested advice.");
        rules.add("Rule #265: The customer is always right... until you get their Latinum.");
        rules.add("Rule #266: When in doubt, lie.");
        rules.add("Rule #267: If you believe it, they believe it.");
        rules.add("Rule #268: Hold on to what you have, but plan for future luck.");
        rules.add("Rule #269: Trying to please an enemy makes you the loser everytime.");
        rules.add("Rule #270: In business deals, a disruptor can be almost as important as a calculator.");
        rules.add("Rule #271: What we want is not always the most profitable.");
        rules.add("Rule #272: Think twice before leaping once.");
        rules.add("Rule #273: Don't waste your breath arguing with a Klingon; save it for the running you may have to do.");
        rules.add("Rule #274: Consider your next transaction while counting your Latinum.");
        rules.add("Rule #275: Foolish investment based on foolish advice is still foolish investment.");
        rules.add("Rule #276: Overbooking is standard practice.");
        rules.add("Rule #277: Anything worth fighting for is worth hiding from.");
        rules.add("Rule #278: Appearances are deceptive. Dress above yourself.");
        rules.add("Rule #279: Necessity knows no price.");
        rules.add("Rule #280: If it ain't broke, don't fix it.");
        rules.add("Rule #281: Greed cannot overreach itself.");
        rules.add("Rule #282: The value of something is not in its use, but in its price.");
        rules.add("Rule #283: An individual is smart, a group is not.");
        rules.add("Rule #284: Deep down, everyone's a Ferengi.");
        rules.add("Rule #285: No good deed ever goes unpunished.");
        rules.add("The Unwritten Rule: When no appropriate Rule applies, make one up!");
    }

    // return a random rule from list
    public String getRandomRule() {
        Random rand = new Random();
        return rules.get(rand.nextInt(rules.size()));
    }
}
